### ISSUE TITLE
GSoD'19 Applicant

### ISSUE THREAD

**Issue by tapaswenipathak** [OWASP/SecureTea-Project#145]
Hi folks, 

I am a GSoD'19 applicant for SecureTea-Project. I was reading the tickets and documentation work for applicant. I didn't find any open docs labelled tickets in this repository. I have been a OWASP SoC intern in '15 I think for OWASP/hackademic. Can you please let me know any tickets that I can solve in application period? I know there are few days remaining in application deadline, feel free in letting me know any tickets, mostly will close in a day. Just as an example I worked on a GSoD org where doc tickets were opened after I suggested, so if you can open few doc tickets, would be great! Thanks, Tapasweni.

**Comment by adeyosemanputra** [comment]
for docs
https://github.com/OWASP/SecureTea-Project/issues/62
and lets disscuss by telegram group https://github.com/OWASP/SecureTea-Project/issues/62
