### ISSUE TITLE
Getting errors while setting up readthedocs.

### ISSUE THREAD

**Issue by sunn-e** [OWASP/SecureTea-Project#150]
steps to reproduce.
Clone my repo which has new docs built with sphinx.
-  `git clone https://github.com/sunn-e/SecureTea-Project.git` in a new folder.
-   Open your readthedocs.org account and import the project for doc build up on the site.
-   You will get an error. Below raw text is given. Is there any way we can resolve this? There is now interface to do that in readthedocs console as far as I know. @abhisharma404 @rejahrehim @adeyosemanputra Please have a look into it. 

` Read the Docs build information
Build id: 9306347
Project: securetea-project
Version: latest
Commit: 88c6948d0d19633d7ef8b6a1dea057cc7683434b
Date: 2019-07-01T11:40:18.814424Z
State: finished
Success: False

[rtd-command-info] start-time: 2019-07-01T11:40:19.174589Z, end-time: 2019-07-01T11:40:19.186390Z, duration: 0, exit-code: 0
git remote set-url origin https://github.com/sunn-e/SecureTea-Project.git

[rtd-command-info] start-time: 2019-07-01T11:40:19.247385Z, end-time: 2019-07-01T11:40:19.522849Z, duration: 0, exit-code: 0
git fetch --tags --prune --prune-tags --depth 50
From https://github.com/sunn-e/SecureTea-Project
   06cc9e8..88c6948  master     -> origin/master

[rtd-command-info] start-time: 2019-07-01T11:40:19.765645Z, end-time: 2019-07-01T11:40:19.867273Z, duration: 0, exit-code: 0
git checkout --force origin/master
Previous HEAD position was 06cc9e8 removing conflicts in docs
HEAD is now at 88c6948 Merge pull request #8 from sunn-e/sphinx

[rtd-command-info] start-time: 2019-07-01T11:40:19.956081Z, end-time: 2019-07-01T11:40:19.971266Z, duration: 0, exit-code: 0
git clean -d -f -f

[rtd-command-info] start-time: 2019-07-01T11:40:33.832125Z, end-time: 2019-07-01T11:40:39.620391Z, duration: 5, exit-code: 0
python3.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest
Using base prefix '/home/docs/.pyenv/versions/3.7.3'
New python executable in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/bin/python3.7
Not overwriting existing python script /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/bin/python (you must use /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/bin/python3.7)
Installing setuptools, pip, wheel...
done.

[rtd-command-info] start-time: 2019-07-01T11:40:39.704979Z, end-time: 2019-07-01T11:40:40.699929Z, duration: 0, exit-code: 0
/home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/bin/python -m pip install --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/.cache/pip pip
Requirement already up-to-date: pip in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (19.1.1)

[rtd-command-info] start-time: 2019-07-01T11:40:40.823247Z, end-time: 2019-07-01T11:40:44.046281Z, duration: 3, exit-code: 0
/home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/bin/python -m pip install --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/.cache/pip Pygments==2.3.1 setuptools==41.0.1 docutils==0.14 mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<0.7
Requirement already up-to-date: Pygments==2.3.1 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (2.3.1)
Requirement already up-to-date: setuptools==41.0.1 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (41.0.1)
Requirement already up-to-date: docutils==0.14 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (0.14)
Requirement already up-to-date: mock==1.0.1 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (1.0.1)
Requirement already up-to-date: pillow==5.4.1 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (5.4.1)
Requirement already up-to-date: alabaster!=0.7.5,<0.8,>=0.7 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (0.7.12)
Requirement already up-to-date: commonmark==0.8.1 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (0.8.1)
Requirement already up-to-date: recommonmark==0.5.0 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (0.5.0)
Requirement already up-to-date: sphinx<2 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (1.8.5)
Requirement already up-to-date: sphinx-rtd-theme<0.5 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (0.4.3)
Requirement already up-to-date: readthedocs-sphinx-ext<0.7 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (0.6.0)
Requirement already satisfied, skipping upgrade: future in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from commonmark==0.8.1) (0.17.1)
Requirement already satisfied, skipping upgrade: packaging in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from sphinx<2) (19.0)
Requirement already satisfied, skipping upgrade: six>=1.5 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from sphinx<2) (1.12.0)
Requirement already satisfied, skipping upgrade: requests>=2.0.0 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from sphinx<2) (2.22.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.3 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from sphinx<2) (2.10.1)
Requirement already satisfied, skipping upgrade: imagesize in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from sphinx<2) (1.1.0)
Requirement already satisfied, skipping upgrade: sphinxcontrib-websupport in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from sphinx<2) (1.1.2)
Requirement already satisfied, skipping upgrade: babel!=2.0,>=1.3 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from sphinx<2) (2.7.0)
Requirement already satisfied, skipping upgrade: snowballstemmer>=1.1 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from sphinx<2) (1.9.0)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from packaging->sphinx<2) (2.4.0)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from requests>=2.0.0->sphinx<2) (2.8)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from requests>=2.0.0->sphinx<2) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from requests>=2.0.0->sphinx<2) (2019.6.16)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from requests>=2.0.0->sphinx<2) (1.25.3)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from Jinja2>=2.3->sphinx<2) (1.1.1)
Requirement already satisfied, skipping upgrade: pytz>=2015.7 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from babel!=2.0,>=1.3->sphinx<2) (2019.1)

[rtd-command-info] start-time: 2019-07-01T11:40:44.169909Z, end-time: 2019-07-01T11:40:49.827547Z, duration: 5, exit-code: 1
/home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/bin/python -m pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/.cache/pip -r requirements.txt
Requirement already satisfied: requests in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: requests_oauthlib in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: py_cpuinfo in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (5.0.0)
Requirement already satisfied: psutil in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (5.6.3)
Requirement already satisfied: flask in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (1.0.3)
Requirement already satisfied: flask_cors in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (3.0.8)
Requirement already satisfied: pynput in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (1.4.2)
Requirement already satisfied: python-telegram-bot in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (11.1.0)
Requirement already satisfied: twilio in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (6.29.0)
Requirement already satisfied: scapy in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (2.4.2)
Collecting NetfilterQueue (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/39/c4/8f73f70442aa4094b3c37876c96cddad2c3e74c058f6cd9cb017d37ffac0/NetfilterQueue-0.8.1.tar.gz
Collecting boto3 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/3b/6e/8189e561e15eb0def4f3155ab4addf231891b2df2216495fc58a5049af55/boto3-1.9.180-py2.py3-none-any.whl
Collecting geocoder (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/4f/6b/13166c909ad2f2d76b929a4227c952630ebaf0d729f6317eb09cbceccbab/geocoder-1.38.1-py2.py3-none-any.whl
Collecting pathlib (from -r requirements.txt (line 14))
Requirement already satisfied: certifi>=2017.4.17 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (2019.6.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (1.25.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: oauthlib>=3.0.0 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from requests_oauthlib->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: itsdangerous>=0.24 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from flask->-r requirements.txt (line 5)) (1.1.0)
Requirement already satisfied: Werkzeug>=0.14 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from flask->-r requirements.txt (line 5)) (0.15.4)
Requirement already satisfied: click>=5.1 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from flask->-r requirements.txt (line 5)) (7.0)
Requirement already satisfied: Jinja2>=2.10 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from flask->-r requirements.txt (line 5)) (2.10.1)
Requirement already satisfied: Six in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from flask_cors->-r requirements.txt (line 6)) (1.12.0)
Requirement already satisfied: python-xlib>=0.17; "linux" in sys_platform in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from pynput->-r requirements.txt (line 7)) (0.25)
Requirement already satisfied: cryptography in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from python-telegram-bot->-r requirements.txt (line 8)) (2.7)
Requirement already satisfied: future>=0.16.0 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from python-telegram-bot->-r requirements.txt (line 8)) (0.17.1)
Requirement already satisfied: PyJWT>=1.4.2 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from twilio->-r requirements.txt (line 9)) (1.7.1)
Requirement already satisfied: pytz in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from twilio->-r requirements.txt (line 9)) (2019.1)
Requirement already satisfied: pysocks; python_version >= "3.0" in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from twilio->-r requirements.txt (line 9)) (1.7.0)
Collecting botocore<1.13.0,>=1.12.180 (from boto3->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/3b/27/fa7da6feb20d1dfc0ab562226061b20da2d27ea18ca32dc764fe86704a99/botocore-1.12.180-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting s3transfer<0.3.0,>=0.2.0 (from boto3->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/16/8a/1fc3dba0c4923c2a76e1ff0d52b305c44606da63f718d14d3231e21c51b0/s3transfer-0.2.1-py2.py3-none-any.whl
Collecting ratelim (from geocoder->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/f2/98/7e6d147fd16a10a5f821db6e25f192265d6ecca3d82957a4fdd592cad49c/ratelim-0.1.6-py2.py3-none-any.whl
Requirement already satisfied: MarkupSafe>=0.23 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from Jinja2>=2.10->flask->-r requirements.txt (line 5)) (1.1.1)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from cryptography->python-telegram-bot->-r requirements.txt (line 8)) (1.12.3)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from cryptography->python-telegram-bot->-r requirements.txt (line 8)) (0.24.0)
Requirement already satisfied: docutils>=0.10 in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from botocore<1.13.0,>=1.12.180->boto3->-r requirements.txt (line 12)) (0.14)
Collecting python-dateutil<3.0.0,>=2.1; python_version >= "2.7" (from botocore<1.13.0,>=1.12.180->boto3->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting decorator (from ratelim->geocoder->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Requirement already satisfied: pycparser in /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->python-telegram-bot->-r requirements.txt (line 8)) (2.19)
Building wheels for collected packages: NetfilterQueue
  Building wheel for NetfilterQueue (setup.py): started
  Building wheel for NetfilterQueue (setup.py): finished with status 'error'
  Running setup.py clean for NetfilterQueue
  ERROR: Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-aorse33s/NetfilterQueue/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-fadh0nxb --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_ext
  building 'netfilterqueue' extension
  creating build
  creating build/temp.linux-x86_64-3.7
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/docs/.pyenv/versions/3.7.3/include/python3.7m -c netfilterqueue.c -o build/temp.linux-x86_64-3.7/netfilterqueue.o
  netfilterqueue.c:437:10: fatal error: libnfnetlink/linux_nfnetlink.h: No such file or directory
   #include "libnfnetlink/linux_nfnetlink.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for NetfilterQueue
Failed to build NetfilterQueue
Installing collected packages: NetfilterQueue, python-dateutil, jmespath, botocore, s3transfer, boto3, decorator, ratelim, geocoder, pathlib
  Running setup.py install for NetfilterQueue: started
    Running setup.py install for NetfilterQueue: finished with status 'error'
    ERROR: Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-aorse33s/NetfilterQueue/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pyq45zkj/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/include/site/python3.7/NetfilterQueue:
    ERROR: running install
    running build
    running build_ext
    building 'netfilterqueue' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/docs/.pyenv/versions/3.7.3/include/python3.7m -c netfilterqueue.c -o build/temp.linux-x86_64-3.7/netfilterqueue.o
    netfilterqueue.c:437:10: fatal error: libnfnetlink/linux_nfnetlink.h: No such file or directory
     #include "libnfnetlink/linux_nfnetlink.h"
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-aorse33s/NetfilterQueue/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pyq45zkj/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/checkouts/readthedocs.org/user_builds/securetea-project/envs/latest/include/site/python3.7/NetfilterQueue" failed with error code 1 in /tmp/pip-install-aorse33s/NetfilterQueue/

`

**Comment by sunn-e** [comment]
Sorry for the long error message but  there were multiple points of failure so I guess it was necessary to include everything.

**Comment by abhisharma404** [comment]
Hi @sunn-e 

Can I have a look at your `.readthedocs.yml`?

Also, have you created a configuration python file especially for `readthedocs`? Also, have you re-created all the docs in `.rst` format?

**Comment by sunn-e** [comment]
Yes @abhisharma404 , I have all of them in .rst format. I did not generate any yml files.

**Comment by goheesheng** [comment]
Nah all the methods provided to install doesn't work. git clone and install requirement.txt, unzipping and download file and install requirement.txt etc.

**Comment by adeyosemanputra** [comment]
@goheesheng are you found the bug or get installation issues?

**Comment by goheesheng** [comment]
![image](https://user-images.githubusercontent.com/77826239/129497732-d6014a01-f64c-4a0d-897e-222dddf337ce.png)

**Comment by goheesheng** [comment]
I have already installed distro yet still the same error

**Comment by adeyosemanputra** [comment]
@goheesheng can you check again? already we fix it?
