### ISSUE TITLE
Depricated Google+ icon in Website footer

### ISSUE THREAD

**Issue by lelouchB** [OWASP/SecureTea-Project#204]
I was going through the securetea official  website when I came a small **google+ icon** in the website footer  which links to the GSoC page, It may be insignificant to many but since google+ was shut down last year, I think the icon should be changed to a **more appropriate icon**

I want to do the same and plan to change the icon to **GSoC icon...**
Shall I go ahead????

![securetea](https://user-images.githubusercontent.com/45850882/62421190-9109f800-b6bb-11e9-95a6-c3f93ca8a70b.png)

**Comment by rejahrehim** [comment]
@lelouchB Can you move this issue to https://github.com/securetea/securetea-web
