### ISSUE TITLE
secuertea is not working

### ISSUE THREAD

**Issue by jishnurippon** [OWASP/SecureTea-Project#234]
**About the bug**
After installing securetea using ``sudo python3 -m pip install securetea`` it will not open.

**Steps**
1. ``sudo python3 -m pip install securetea``
2.  ``sudo securetea.py`` and ``sudo python3 securetea.py``

**Expected behavior**
Run securetea.py

**Screenshots**
![Screenshot from 2019-08-18 01-09-56](https://user-images.githubusercontent.com/48761358/63213056-11ebd980-c129-11e9-8307-fc2bc2c73ba6.png)
![Screenshot from 2019-08-18 01-23-49](https://user-images.githubusercontent.com/48761358/63213104-17e1ba80-c129-11e9-9560-1002652ee09d.png)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu
 - OS version: 18.04.3

**Additional context we should know**
When I try ``sudo SecureTea.py`` it will start.

**Comment by abhisharma404** [comment]
@jishnurippon 
PyPi installation is not running `setup.py` as it should be doing, I'll look into it. Meanwhile, please install using git repo.

```
git clone https://github.com/OWASP/SecureTea-Project.git
cd SecureTea-Project
sudo python3 -m pip install -r requirements.txt
sudo python3 setup.py install
```

Please let me know if this works on not, PyPi needs a lot of improvement for which we need to work a lot. :)

**Comment by rejahrehim** [comment]
@abhisharma404 We need to make it work with PyPi. Everyone will not be ready to install with many commands. We should provide a single command.

**Comment by abhisharma404** [comment]
@jishnurippon Hi there! You have used the wrong command, it's `sudo SecureTea.py` instead of `sudo securetea.py` :)

Try this. :)

Anyway, I'll suggest you to wait for our next release v1.6 very soon and then install again using our PyPi command:
`sudo python3 -m pip install securetea`

There's has been a lot of PyPi bug fixes in the upcoming release.
