### ISSUE TITLE
Unsupported Interfaces is getting into an error loop

### ISSUE THREAD

**Issue by kevinshaji97** [OWASP/SecureTea-Project#235]
**Describe the bug**
After configuration when we try to choose an Interface using the index number if it doesn't support scanning it will end in a loop with message ```Interface doesn't support scanning.```

**To Reproduce**
1. Configure the securetea
2. Run ```sudo python SecureTea.py --server-mode```
3. Choose use saved configuration
4. Choose an unsupported interface from the list of available

**Screenshots**
![Screenshot from 2019-08-17 19-40-25](https://user-images.githubusercontent.com/46342897/63213670-b4598c00-c12c-11e9-9ccd-b6d0872ad6a6.png)
![Screenshot from 2019-08-17 19-32-25](https://user-images.githubusercontent.com/46342897/63213693-01d5f900-c12d-11e9-919b-e213b30e6938.png)

**Desktop (please complete the following information):**
 - Operating System:  Ubuntu
 - OS version:  18.10

**Comment by abhisharma404** [comment]
@kevinshaji97 Hi there, Yup I did notice it, PR #232 fixes this :)

**Comment by adeyosemanputra** [comment]
@kevinshaji97 have you try again and get error? If not this issue should to be close

**Comment by abhisharma404** [comment]
@kevinshaji97 Please update your local repository. This error is a combination of two parts, the following PR fixes them: 
1. PR #226 
2. PR #232
