### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by sam-aldis** [OWASP/SecureTea-Project#241]
Further to our talk on the project committee channel - Over the next few days I'll create a docker container and potentially either lxd or vagrant image for the project so any developers can easily "pull and play" without worrying about setup and environment, please tag me in @rejahrehim

**Comment by amanjiofficial** [comment]
Is this issue still opened?
@rejahrehim

**Comment by prince-7** [comment]
Fixed by https://github.com/OWASP/SecureTea-Project/pull/242
