### ISSUE TITLE
Testing in linux varients 

### ISSUE THREAD

**Issue by rejahrehim** [OWASP/SecureTea-Project#247]
Need to test and report issues on each and every Linux distros

**Comment by rejahrehim** [comment]
@kUSHAL0601  Can you update the status here ?

**Comment by kUSHAL0601** [comment]
SecureTea has been tested on the following linux variants :

1.  Ubuntu 16.04
2.  Ubuntu 20.04
3. CentOS 7
4. Fedora 32
5. Kali linux 2016
6. ParrotSec 4.2

The testing includes installation and unit testing

**Comment by rejahrehim** [comment]
Awesome. Can we put a table in the Readme stating the status and tested OSs @kUSHAL0601

**Comment by kUSHAL0601** [comment]
Sure will do! Although could you clarify on the status part. Should I put error/no error and put some other OSs which we should probably test on ?

**Comment by rejahrehim** [comment]
Passed, Partial, Need  improvement as status also you can put any specific comments too

**Comment by NishantPuri99** [comment]
Hi, is this issue still open? I have a Debian Buster VM?
Any ideas on how to go about it?

**Comment by rejahrehim** [comment]
> Hi, is this issue still open? I have a Debian Buster VM?
> Any ideas on how to go about it?

Still up. You can update the test results

**Comment by NishantPuri99** [comment]
Hi! I tried installing SecureTea on Debian as well as Kali and am facing some errors. I guess it's because of one of the dependencies **NetFilterQueue** to be exact. I tried manually building it from [source](https://github.com/kti/python-netfilterqueue).

**Comment by kUSHAL0601** [comment]
Hi. Did you try using the [bash script](https://github.com/OWASP/SecureTea-Project/blob/master/install_dependencies_apt.sh)? It should help you with installation issues in general!

**Comment by NishantPuri99** [comment]
Yes I did run it, but I encountered this netfilterqueue at that time only.

That is why I tried building from source

**Comment by prince-7** [comment]
NetfilterQueue issue can be fixed in this way https://github.com/OWASP/SecureTea-Project/pull/242. This can be closed.
