### ISSUE TITLE
Unable to complete Installation

### ISSUE THREAD

**Issue by VltraHeaven** [OWASP/SecureTea-Project#248]
I'm unable to install SecureTea on my host.

**To Reproduce**

I run the following commands
```sh
python3 -m venv venv1
source venv1/bin/activate.fish
sudo apt install build-essential python-dev python3-dev libnetfilter-queue-dev
sudo python3 setup.py install
```

and the error that occurs is...
```sh
Best match: NetfilterQueue 0.8.1
Processing NetfilterQueue-0.8.1.tar.gz
Writing /tmp/easy_install-ath_tmjl/NetfilterQueue-0.8.1/setup.cfg
Running NetfilterQueue-0.8.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ath_tmjl/NetfilterQueue-0.8.1/egg-dist-tmp-5_ajvyup
netfilterqueue.c: In function ‘__pyx_f_14netfilterqueue_6Packet_set_nfq_data’:
netfilterqueue.c:2150:68: warning: passing argument 2 of ‘nfq_get_payload’ from incompatible pointer type [-Wincompatible-pointer-types]
   __pyx_v_self->payload_len = nfq_get_payload(__pyx_v_self->_nfa, (&__pyx_v_self->payload));
                                                                   ~^~~~~~~~~~~~~~~~~~~~~~~
In file included from netfilterqueue.c:440:
/usr/include/libnetfilter_queue/libnetfilter_queue.h:122:67: note: expected ‘unsigned char **’ but argument is of type ‘char **’
 extern int nfq_get_payload(struct nfq_data *nfad, unsigned char **data);
                                                   ~~~~~~~~~~~~~~~~^~~~
netfilterqueue.c: In function ‘__pyx_pf_14netfilterqueue_6Packet_4get_hw’:
netfilterqueue.c:2533:17: warning: implicit declaration of function ‘PyString_FromStringAndSize’; did you mean ‘PyBytes_FromStringAndSize’? [-Wimplicit-function-declaration]
     __pyx_t_3 = PyString_FromStringAndSize(((char *)__pyx_v_self->hw_addr), 8); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 111, __pyx_L1_error)
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
                 PyBytes_FromStringAndSize
netfilterqueue.c:2533:15: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
     __pyx_t_3 = PyString_FromStringAndSize(((char *)__pyx_v_self->hw_addr), 8); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 111, __pyx_L1_error)
               ^
netfilterqueue.c: In function ‘__Pyx_PyCFunction_FastCall’:
netfilterqueue.c:6436:13: error: too many arguments to function ‘(PyObject * (*)(PyObject *, PyObject * const*, Py_ssize_t))meth’
     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
netfilterqueue.c: In function ‘__Pyx__ExceptionSave’:
netfilterqueue.c:7132:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     *type = tstate->exc_type;
                     ^~~~~~~~
                     curexc_type
netfilterqueue.c:7133:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
     *value = tstate->exc_value;
                      ^~~~~~~~~
                      curexc_value
netfilterqueue.c:7134:19: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     *tb = tstate->exc_traceback;
                   ^~~~~~~~~~~~~
                   curexc_traceback
netfilterqueue.c: In function ‘__Pyx__ExceptionReset’:
netfilterqueue.c:7141:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
netfilterqueue.c:7142:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
netfilterqueue.c:7143:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
netfilterqueue.c:7144:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tstate->exc_type = type;
             ^~~~~~~~
             curexc_type
netfilterqueue.c:7145:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tstate->exc_value = value;
             ^~~~~~~~~
             curexc_value
netfilterqueue.c:7146:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tstate->exc_traceback = tb;
             ^~~~~~~~~~~~~
             curexc_traceback
netfilterqueue.c: In function ‘__Pyx__GetException’:
netfilterqueue.c:7201:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
netfilterqueue.c:7202:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
netfilterqueue.c:7203:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
netfilterqueue.c:7204:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tstate->exc_type = local_type;
             ^~~~~~~~
             curexc_type
netfilterqueue.c:7205:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tstate->exc_value = local_value;
             ^~~~~~~~~
             curexc_value
netfilterqueue.c:7206:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tstate->exc_traceback = local_tb;
             ^~~~~~~~~~~~~
             curexc_traceback
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Desktop (please complete the following information):**
 - Operating System: Linux, Devuan
 - OS version: Beowulf (Buster) Kernel: SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
 - Python Version: Python 3.7.3
 - GCC Version: gcc (Debian 8.3.0-6) 8.3.0

I also got the same error when attempting to install this on my Arch Linux host two months ago.

**Comment by abhisharma404** [comment]
@VltraHeaven Could you try re-installing NetfilterQueue?

**Comment by jishnurippon** [comment]
**About the bug**
i have the same issue in my parrot OS
```Failed building wheel for NetfilterQueue```

**Screenshots**
![securetea](https://user-images.githubusercontent.com/48761358/70370983-28b26980-189b-11ea-82c6-a6a18b053772.png)



**Desktop (please complete the following information):**
 - Operating System: Parrot
 - OS version: Kernel Linux 4.19.0-parrot4-28t-amd64 x86_64

**Comment by jishnurippon** [comment]
**About the bug**
When i try to install separately. It show the same message.

**Comment by Ashokrnair** [comment]
**About the bug**
i have the same issue in my  Ubuntu 19.04
Running setup.py install for NetfilterQueue . . . error

**Screenshots**
![Screenshot from 2019-12-09 13-03-20](https://user-images.githubusercontent.com/43372601/70417053-69baa180-1a86-11ea-9a81-41b5b03ad03a.png)


**Desktop (please complete the following information):**

- Operating System: Ubuntu 19.04

**Comment by abhisharma404** [comment]
@Ashokrnair 
Could you please try the following commands before:
```
$ sudo apt-get update
$ sudo apt-get install build-essential python-dev libnetfilter-queue-dev
```

**Comment by mbhole1857** [comment]
I have installed the below packages before running the setup.py on python3 still I am getting the **netfilterqueue** error 
sudo apt-get install build-essential python3-dev libcap-dev libnfnetlink-dev libnetfilter-queue-dev

Error Screenshot:
![Screenshot at 2019-12-16 10-01-17](https://user-images.githubusercontent.com/13765264/70879567-df95a000-1f93-11ea-898e-cf53911777f5.png)

**Comment by cciro94** [comment]
I have the same problem. The installation procedure does not end with python3. However, if I install the project with python2.7 the installation has been done, but it doesn't run:

`/usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  'The soupsieve package is not installed. CSS selectors cannot be used.'
[!] Do you want to use the saved configuratons? (Y/y): y
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/stefano/git/SecureTea-Project/SecureTea.py", line 13, in <module>
    secT = SecureTea()
  File "securetea/core.py", line 77, in __init__
    args_dict = argsHelper.check_args()
  File "securetea/args/args_helper.py", line 733, in check_args
    if creds.get("firewall"):
AttributeError: 'NoneType' object has no attribute 'get'
`

**Comment by cciro94** [comment]
> I have the same problem. The installation procedure does not end with python3. However, if I install the project with python2.7 the installation has been done, but it doesn't run:
> 
> `/usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used. 'The soupsieve package is not installed. CSS selectors cannot be used.' [!] Do you want to use the saved configuratons? (Y/y): y Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/home/stefano/git/SecureTea-Project/SecureTea.py", line 13, in <module> secT = SecureTea() File "securetea/core.py", line 77, in __init__ args_dict = argsHelper.check_args() File "securetea/args/args_helper.py", line 733, in check_args if creds.get("firewall"): AttributeError: 'NoneType' object has no attribute 'get' `
> 
> Do you have any solutions?
> 
> Thanks in advance

Solution: 
1. Install python3.8
2. Run:
`
pip3.8 install -U git+https://github.com/kti/python-netfilterqueue
pip3.8 install securetea
pip3.8 install bs4
pip3.8 install wget
pip3.8 install shodan
`

**Comment by prince-7** [comment]
This can be solved by following this PR https://github.com/OWASP/SecureTea-Project/pull/274

**Comment by adeyosemanputra** [comment]
done thank you @prince-7
