### ISSUE TITLE
Error in listener callback

### ISSUE THREAD

**Issue by Gincy1226** [OWASP/SecureTea-Project#251]
**ERROR - HTTPConnectionPool**

Token and User ID is given and got an error when run the command :

```$python SecureTea.py```

**Error**

![Screenshot from 2019-12-07 19-25-32 (2)](https://user-images.githubusercontent.com/46300157/70375916-91e0be00-1929-11ea-8ae3-6f36cd44d2d9.png)

**Desktop:**
 - Operating System: Ubuntu
 - OS version:  18.04
 - Python :Python 3.6.9
 - Pip : pip 9.0.1

**Comment by adeyosemanputra** [comment]
try python3 SecureTea.py

**Comment by Gincy1226** [comment]
Thank you. Issue resolved

**Comment by adeyosemanputra** [comment]
ok  good luck
