### ISSUE TITLE
Restructuring the current project architecture

### ISSUE THREAD

**Issue by abhisharma404** [OWASP/SecureTea-Project#32]
Currently, we have all the files in the major folder i.e. `securetea` folder itself.
A better way to organize would to be group the commons in a separate folder.
For example, the following structure: 
```
securetea/
    |__lib/
          |__notif/
                |__ __init__.py
                |__secureTeaTwitter.py
                |__secureTeaTwilio.py
                |__secureTeaTelegram.py
                |__secureTeaSlack.py
   |__args/
         |__arguments.py
         |__args_helper.py
  |__ __init__.py
  |__common.py
  |__core.py
  |__logger.py
  |__configurations.py
```
As per the roadmap, other features like Firewall, IDS, Intelligent Log Montioring, AntiVirus can all be added to the `securetea/lib` folder, by creating respective folders.

If yes, I would like to work on this.

**Comment by abhisharma404** [comment]
@rejahrehim Any thoughts on this? Shall this be worked upon?

**Comment by rejahrehim** [comment]
@abhisharma404 You can work on this
