### ISSUE TITLE
typo on the project demo section

### ISSUE THREAD

**Issue by shubhangi013** [OWASP/SecureTea-Project#325]
It should be **IoT** and not **IOT**
![Screenshot from 2021-09-09 14-52-01](https://user-images.githubusercontent.com/78342516/132661195-fdcb8a8c-b62c-4731-b60c-c4a92999d3dd.png)

**Comment by adeyosemanputra** [comment]
@shubhangi013 where is the typo which you find? at the securetea website?

**Comment by shubhangi013** [comment]
> @shubhangi013 where is the typo which you find? at the securetea website?

yeah at the securetea website

**Comment by adeyosemanputra** [comment]
@shubhangi013 thank you for your information. will update as soon and closed this issues because the typo not in this repo. it's outside this repo.
