### ISSUE TITLE
GUI needs a makeover

### ISSUE THREAD

**Issue by DigvijayBhosale1729** [OWASP/SecureTea-Project#341]
**Describe the bug**
Gui is becoming outdated. The View changes fonts as i scroll and sometimes, security features dont work. 

**To Reproduce**
1. While installing Angular and setting up project, 41 vulnerabilities (1 low, 16 moderate, 24 high) are displayed
2. Start GUI by `ng serve` in `gui` folder and `python3 run.py` in 
3. Register/login on `http://127.0.0.1:4200/`
4. Try scrolling down. The font changes on scroll.
5. In security section, too much information is shown to user. Navigation to one single section or one single tool is difficult. 

**Expected behavior**
GUI should be simplistic, easy to use and concise 
For a developer, understanding new logic should be easy. In current GUI, understanding logic is difficult. 

**Why this may have happened according to you**
I believe that this issue is because the GUI is outdated and because of flask. 

An ideal solution would be -
- creating a new GUI app with Angular frontend and Python Django Backend
- using only LTS modules in project to minimize the vulnerabilities that arise from modules
- at backend, use command line to execute commands and show command line output in GUI window - similar to ZenMap and Armitage, making users more comfortable with the CLI as a side product.
- have strong backend support to handle each different task in a proper and efficient way with focus on the command line. 

**Desktop (please complete the following information):**
 - Ubuntu
 - 20.04.3 LTS
 - FireFox
 - 92.0.1

**Additional context we should know**

**Comment by kUSHAL0601** [comment]
Does not make sense to change the server from flask to django when angular gui had version issues. Usually such issues arise because npm lock of angular needs to be updated and that should be a good fix. Also using django gives no supremacy ocer using flask...
