### ISSUE TITLE
Notification via Mail (Gmail API)

### ISSUE THREAD

**Issue by Vipul999ujawane** [OWASP/SecureTea-Project#36]
Currently the App project has notifications via:
Twilio (SMS)
Telegram
Slack

Another Notification channel can be Email

-> Solution : 
Use of the gmail api to send mails to a select user

**Comment by Vipul999ujawane** [comment]
@rejahrehim , can I work on the issue?

**Comment by rejahrehim** [comment]
Yes, But provide provisions to integrate popular email providers like Sendgrid, Amazon SES etc.

**Comment by Vipul999ujawane** [comment]
Ok, will do!

**Comment by sunn-e** [comment]
Hey, I would like to give it a try too. I'm interested in GSOC.

**Comment by rejahrehim** [comment]
@sunn-e You could try implementing any one of this email provider.

**Comment by adeyosemanputra** [comment]
#70
