### ISSUE TITLE
Log Monitoring and Login History Using Linux Log file

### ISSUE THREAD

**Issue by jay13patel** [OWASP/SecureTea-Project#38]
Problem : 
Currently, the App project has no log monitoring and login history 

Solution:-
By using capabilities of log files generated by every OS, especially in Linux log files are generated by that we can monitor every step which user can notify if anyone used a pen drive or malicious device without the user permission and  is injected in it with attacker have physical access to the system

**Comment by jay13patel** [comment]
@rejahrehim, can I work on the issue?

**Comment by rejahrehim** [comment]
@jay13patel you can start working on detecting and disabling/enabling external drives like a pen drive. @mishal23 is working on parsing system logs. I think you both can work together.

**Comment by jay13patel** [comment]
Ok I will collaborate with @mishal23  for the detection of malicious devices and also want to work on implementing netfilter firewall in this project and want to implement more security levels (like host based IDS/IPS) in it.

**Comment by rejahrehim** [comment]
Okay, stat with the log monitor now.

**Comment by adeyosemanputra** [comment]
Its good ideas @rejahrehim @jay13patel to detect malicious device like bad usb,  usb rubber ducky and bash bunny https://github.com/hak5/bashbunny-payloads/

**Comment by jay13patel** [comment]
#67 Feature : Detection of malicious devices

**Comment by jay13patel** [comment]
#67

**Comment by jay13patel** [comment]
#67

**Comment by abhisharma404** [comment]
@rejahrehim @adeyosemanputra This issue can be closed, as PR #126 implements everything.

**Comment by abhisharma404** [comment]
@rejahrehim @adeyosemanputra This issue can be closed, as PR #126 implements everything.
