### ISSUE TITLE
KeyLogging Features.

### ISSUE THREAD

**Issue by Tikam02** [OWASP/SecureTea-Project#40]
**Is your feature request related to a problem? Please describe.**
If someone unauthorized  log in to the system and do some malicous activity then all the key logs were mailed to the user.

**Describe the solution you'd like**
A Smart key-logger script.
1) First,basic keylogger that mails key logs to user.
2) Second,Implementation smart user keylogger that classifies normal user and anamoly user.

**Comment by adeyosemanputra** [comment]
Do u mean to add keyloging feature into SecureTea Project @Tikam02

**Comment by Tikam02** [comment]
@adeyosemanputra  Yeah.

**Comment by Tikam02** [comment]
@adeyosemanputra can I contribute to this by adding this feature.

**Comment by abhisharma404** [comment]
@Tikam02 How do you plan to implement categorizing user?

**Comment by Tikam02** [comment]
@abhisharma404  Actually I was planning to Categorize user based on their USER Behavior using Machine Learning implementing that will take time, then I was exploring other optimized and easier  ML methods to categorize user on their user behaviour. Yeah it is possible and can be implemented.
