### ISSUE TITLE
Need someone to deploy owasp securetea gui / dashboard into herokuapp

### ISSUE THREAD

**Issue by adeyosemanputra** [OWASP/SecureTea-Project#42]
Hi @mishal23 @abhisharma404 
If possible in the end we should deploy owasp securetea dashboard into herokuapp

Like owasp juice shop
https://juice-shop.herokuapp.com
Best

**Comment by rejahrehim** [comment]
This dashboard should be a demo. As we could not deploy a dashboard for everyone.

**Comment by mishal23** [comment]
The dashboard is now deployed here: https://secure-tea.herokuapp.com/dashboard
A sample endpoint is deployed here for a demo: https://securetea-endpoint.herokuapp.com/

You can also start the endpoint app locally using `sudo python monitor.py`, and find your IP Address and enter on the `/config` route to get the statistics on dashboard.

**Comment by rejahrehim** [comment]
@mishal23 Good  :+1:

**Comment by mishal23** [comment]
Sure, also there were small changes made to make the deployment proper.
Shall I send a PR with those changes too? @rejahrehim

**Comment by rejahrehim** [comment]
> Shall I send a PR with those changes too? @rejahrehim
Is that changes specific to Heroku Deployment? 
If yes, keep it in a separate branch. If not, send PR.

**Comment by mishal23** [comment]
Okay. Thank you.
