### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by adeyosemanputra** [OWASP/SecureTea-Project#43]
*Submit Pr related Manual Guide, Installation, Setting / Configuration of OWASP SecureTea Tools Project*

A clear and concise description of Documentation. So user easy to install, configure, running this tools [...]

*where I must submit*
master/doc/user_guide.md or other
master/doc/yourideas.md

**Comment by adeyosemanputra** [comment]
@abhisharma404

**Comment by abhisharma404** [comment]
@adeyosemanputra Sure! :) will send my PR soon.

**Comment by abhisharma404** [comment]
@adeyosemanputra Could you please have a look at the documentation on my forked repo.
Here is the link: https://github.com/abhisharma404/SecureTea-Project/blob/user-guide/doc/user_guide.md

If this is what you were expecting? Please let me know :)

**Comment by adeyosemanputra** [comment]
@abhisharma404 So far it's good  . Waiting @rejahrehim review too.how about you @rejahrehim !
