### ISSUE TITLE
SecureTea Web Defacement and Intrusion Monitoring Tool

### ISSUE THREAD

**Issue by adeyosemanputra** [OWASP/SecureTea-Project#44]
SecureTea Web Defacement and Intrusion Monitoring Tool Modul
based on research https://www.researchgate.net/publication/320101622_Web_Defacement_and_Intrusion_Monitoring_Tool_WDIMT
module for detect web deface and monitoring web if we put SecureTea Tool in the server

**Comment by abhisharma404** [comment]
@adeyosemanputra Working on it.
