### ISSUE TITLE
The user guide and developer guides on OWASP official SecureTea project site are redirecting to 404 page.

### ISSUE THREAD

**Issue by sunn-e** [OWASP/SecureTea-Project#61]
1. Visit: https://www.owasp.org/index.php/OWASP_SecureTea_Project
2. Scroll down to user guide and developer guide section
3. Click on the links
Both the links redirect to a 404.
Cause: The link is not pointing to correct files/files are rearranged without taking website links into account
Solution: Simply rearranging the files in a folder named in following links trail would be easy solution.
Other would be to call website admin and have them update below mentioned links.
link 1: https://github.com/OWASP/SecureTea-Project/blob/master/doc/dev_guide.md
link 2: https://github.com/OWASP/SecureTea-Project/blob/master/doc/user_guide.md
Please look into it.

**Comment by rejahrehim** [comment]
@adeyosemanputra

**Comment by adeyosemanputra** [comment]
Will fix tomorrow 😬😬😬

**Comment by adeyosemanputra** [comment]
@sunn-e do u can help with to make video
Installation securetea project like this
https://m.youtube.com/watch?v=Fsx3H5g_tPQ

**Comment by sunn-e** [comment]
I can @adeyosemanputra

**Comment by sunn-e** [comment]
Can you please elaborate on to what kind of video to be made. I believe we all can have discussion on how the video should be. @rejahrehim @adeyosemanputra

**Comment by adeyosemanputra** [comment]
The Video content about installation,  running the module and securetea.py in many various operating system as u can do it. Windows, linux and Mac0s

**Comment by sunn-e** [comment]
All right.

**Comment by sunn-e** [comment]
Done for Telegram.
