### ISSUE TITLE
Make video for installation 

### ISSUE THREAD

**Issue by adeyosemanputra** [OWASP/SecureTea-Project#62]
@sunn-e do u can help with to make video
Installation securetea project like this
https://m.youtube.com/watch?v=Fsx3H5g_tPQ

**Comment by sunn-e** [comment]
Yes @adeyosemanputra . Should I make an identical video? Do you have any idea?

**Comment by adeyosemanputra** [comment]
The video just for user guide

**Comment by sunn-e** [comment]
I think we should close this @adeyosemanputra . I have sent you the telgram version of installation(user guide)

**Comment by sunn-e** [comment]
@adeyosemanputra Twilio version is done too.

**Comment by adeyosemanputra** [comment]
Gmail/email/slack should be done too!

**Comment by sunn-e** [comment]
https://www.youtube.com/channel/UCGdl9tpc1qZYcM3WRRFRPPA Thanks for creating this channel. It will help to reach more contributors.

**Comment by sunn-e** [comment]
I wanted to do the twitter version but  currently I do not have twitter developer account. I will apply for oneor take help of someone for the demo.

**Comment by abhisharma404** [comment]
@sunn-e I watched both the video. Great work! Much appreciated :+1:.
Also, if you want I can DM you the twitter credentials.

**Comment by sunn-e** [comment]
@abhisharma404 Thanks for the kind words. I'm applying for developer account from another account. Let's hope it gets accepted. Even if that doesn't work, I'll ask you for credentials. 😄

**Comment by abhisharma404** [comment]
@sunn-e Can you update the status on this? Can this be closed?

**Comment by adeyosemanputra** [comment]
still need update for video!

**Comment by sunn-e** [comment]
> 
> 
> @sunn-e I watched both the video. Great work! Much appreciated 👍.
> Also, if you want I can DM you the twitter credentials.

This will be closed probably after GSoD.
 ;)

**Comment by adeyosemanputra** [comment]
Yes if i got best technical writer 😊

**Comment by rejahrehim** [comment]
@all-contributors add @sunn-e for bug

**Comment by GouravRDutta** [comment]
what is the location of log file...?
