### ISSUE TITLE
Difference in licenses

### ISSUE THREAD

**Issue by sunn-e** [OWASP/SecureTea-Project#79]
1. The license over here https://www.owasp.org/index.php/OWASP_SecureTea_Project is GNU Affero General Public License 3.0 
2. And over here  https://github.com/OWASP/SecureTea-Project/blob/master/LICENSE it is MIT. 

This may help- https://stackoverflow.com/questions/3902754/mit-vs-gpl-license

**Comment by rejahrehim** [comment]
Thinking the same, We have to update the license based on the OWASP project standards.

**Comment by sunn-e** [comment]
@rejahrehim @adeyosemanputra  but problem is , different project follows different license.
This is what I found out-

- Glue,NodeFoat,Amass use Apache 2.0
- O-Saft uses GPL 2.0
- SecurityShepherd uses GPL 3.0
- SEDATED uses BSD-3-Clause

**Comment by sunn-e** [comment]
We  can figure this out with mentors of  other projects.

**Comment by sunn-e** [comment]
@adeyosemanputra @rejahrehim I think we need do keep this open untill the license is fixed. What do you think?

**Comment by sunn-e** [comment]
All right. MIT license it is.

**Comment by adeyosemanputra** [comment]
🔚😬
